### PR TITLE
Adds edge cases, tests, errors

### PR DESCRIPTION
**Pull request by bahmady**
@arnau I'm going to work on some tests later or tomorrow but just wanted to get this out because I finally did it (I think...) 

So not looking for approval until it has tests, but just want to know if I have missed something. 

I'm not going to admit how long this took me 👀

### CODE REVIEW

**Comment by arnau** [comment]
Almost perfect, nice :)

Two comments: Remember removing the things that don't belong to Grid like `#loop`. Also you don't really need `@x` and `@y`. You could keep this as part of `cell` by simply operate `x` and `y` there.

**Comment by bahmady** [comment]
@arnau I think I've reached my limit with this: I just can't figure out how to make it work with the (max,max) edge case—i.e. for a 4x4 grid, I can't get `neighbours` to work because `cell` keeps falling down when it reaches the 5th index in the `neighbours` array that requires `x+1` and therefore exceeds `x` so `cell[x][y]` fails. I don't understand why it only seems to mess up with `x`, and I can't figure out how to solve it...

**Comment by arnau** [comment]
For what I can guess, you are trying to get neighbours for an out of range cell. For a grid 5 x 5 the highest index is 4 not 5. But hard to guess from your code.

Below is my take on the problem. Notice that in order for this code to work, you need to add the require for `errors.rb`.

In a gist, the solution is to control when a coordinate is valid or not. And to ensure you know what types of coordinates you want to expect. That means that you must be rigorous with dimensions, coordinates and array indexes because arrays start at 0 and end at n - 1. So, when we say that a grid is 5 x 5 but the highest cell is at (4, 4) because so far you are dealing with coordinates that are indexes.

```ruby
# grid.rb
module Minesweeper

  class Grid
    def initialize(x, y)
      @grid = []

      (0...x).each do ||
        row = []

        (0...y).each do ||
          row << Cell.new
        end

        @grid << row
      end

      @rows = @grid.count
      @columns = @grid[0].count
    end

    attr_accessor :rows
    attr_accessor :columns

    def out_of_range?(x, y)
      raise(Minesweeper::Errors::OutOfRange, [x, y]) if x < -1 || y < -1 || x > @rows || y > @columns
    end

    def cell(x, y)
      out_of_range?(x, y)
      return nil if underflow?(x, y) || overflow?(x, y)

      @grid[x][y]
    end

    def neighbours(x, y)
      [
        cell(x - 1, y + 1),
        cell(x - 1, y),
        cell(x - 1, y - 1),
        cell(x, y + 1),
        cell(x, y - 1),
        cell(x + 1, y + 1),
        cell(x + 1, y),
        cell(x + 1, y - 1)
      ].compact
    end

    def unseal(x, y)
      unless cell(x, y).open?
        cell(x, y).open
      end
    end

    def dimensions
      [@rows, @columns]
    end

    def num_cells
      @rows * @columns
    end

    def num_mines(x, y)
      neighbours(x, y).count { |n| n.mine? }
    end

    private
    def overflow?(x, y)
      x > (@rows - 1) || y > (@columns - 1)
    end

    def underflow?(x, y)
      x < 0 || y < 0
    end
  end
end```

And tests for it:

```ruby
# grid_spec.rb excerpt

describe Minesweeper::Grid do
  it "should produce a grid of the given dimensions" do
    actual = Minesweeper::Grid.new(2,5)
    expect(actual.dimensions).to eq([2,5])
  end

  it "should produce cells that stay open when they are unsealed" do
    actual = Minesweeper::Grid.new(5,5)
    actual.unseal(2,2)
    expect(actual.cell(2,2).open?).to eq(true)
  end

  describe "#neighbours" do
    it "should return 8 neighbours for a centered cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(3, 3)

      expect(actual.length).to eq(8)
    end

    it "should return 5 neighbours for an edge cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(0, 3)

      expect(actual.length).to eq(5)
    end

    it "should return 3 neighbours for the top-left cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(0, 0)

      expect(actual.length).to eq(3)
    end

    it "should return 3 neighbours for the bottom-left cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(0, 4)

      expect(actual.length).to eq(3)
    end

    it "should return 3 neighbours for the top-right cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(4, 0)

      expect(actual.length).to eq(3)
    end

    it "should return 3 neighbours for the bottom-right cell" do
      grid = Minesweeper::Grid.new(5, 5)
      actual = grid.neighbours(4, 4)

      expect(actual.length).to eq(3)
    end

    it "should raise out of range" do
      grid = Minesweeper::Grid.new(5, 5)

      expect { grid.neighbours(5, 5) }.to raise_error(Minesweeper::Errors::OutOfRange)
    end

  end
end```

And you might have noticed a reference to `OutOfRange`:

```ruby
# errors.rb

module Minesweeper
  module Errors
    class OutOfRange < StandardError
      def initialize(coord)
        super("Coordinate (#{coord[0]}, #{coord[1]}) out of range")
      end
    end
  end
end```

**Comment by bahmady** [comment]
OK 😅 there's quite a lot of new stuff there. It makes sense, though, I think: but I'll have to look through it all.

**Comment by bahmady** [comment]
Thank you for spending the time to put all that together, @arnau

**Pull request merged**
