### PR TITLE
Attempt at adding mutating grid (...?)

### PR DESCRIPTION
**Pull request by bahmady**
@arnau I know how I would write tests for this but I'd like to see if this is the right thinking—I'm not sure if what I'm doing qualifies as "mutating" the grid since all I've done is invent an attribute for `cell` called `value`.

### CODE REVIEW

**Comment by bahmady** [comment]
@arnau I've read about methods like `replace` and `freeze` and I know several methods to change the value of something in an array—but what I've put in this PR made the most sense to me, intuitively. 

What I've put in `playground.rb` is really just me messing around "proving" that it works (like I said, I know how I'd write tests but it's more important to me to know that this is what you had in mind).

**Comment by arnau** [comment]
> @arnau I know how I would write tests for this but I'd like to see if this is the right thinking

The right thinking is to make tests and see if it does what you think it should do. If so, it is a solution, if not, it is not.

**Comment by bahmady** [comment]
@arnau how's this?

**Comment by arnau** [comment]
Much better I'd say, how do you feel about it?

**Comment by bahmady** [comment]
I feel good about it :D. I think it's consistent with the rest of the code stylistically and it has tests that demonstrate its efficacy. It also doesn't add any useless or redundant structures.

**Comment by bahmady** [comment]
@arnau so if this looks OK I'll merge it. What's next? :D

**Pull request merged**
